QuizText=[
    #クイズの問題文を入力する
    "このプログラムが書かれている言語は何?",#q1
    "このプログラムのバージョンは?数字とピリオド(.)だけで答えてね",#q2
    "1+2+3+4+5+6+7+8+9=?",#q3
    "このプログラムを実行するのに使うファイルは?数字で答えてね\
\n1: imp1.py\t2: imp2.py\t3: imp3.py\t4: q1_main.py/main.py/など",#q4
    "v1.0からv1.0.1にプログラムのバージョンが変わったとき,一時的に追加された要素は何でしょう?数字で答えてね\
\n1: コマンド機能\t2: クイズ情報インポート\t3: ヒント機能\t4: 変数の量を極端に減らす",#q5
    "このプログラムが開発された日は2025年10月何日?数字で答えてね。",#q6
    "v1.2で追加予定の要素は何でしょう。\
\n1: コマンド機能\t2: クイズ情報インポート\t3: ヒント機能\t4: プログラム全変更",#q7
    "このプログラムv1.1で、imp1.pyは何をするファイルでしょう\
\n1: 問題管理プログラム\t2: 問題編集場所\t3: 変換テーブル\t4: 変換テーブル用リスト\t5: メインシステム",#q8
    "私のNoteアカウント名を入力せよ。ただし'スペース'は無いものとする。",#q9
    "私がプログラミングを始めたきっかけは?\
\n1: いつも意地悪ばっかりしてくる友達に仕返しするため\t2: AIに勧められたから\t3: 友達がScratchで遊んでたから\t4: 英語を覚えたかったから",#q10
    "私が一番最初に学んだプログラミング言語は?\
\n1: Python\t2: JavaScript\t3: Java \t4: C言語など(C++/C# etc)\t5: Scratch\t6: Bash",#q11
    "私が一番制作しているプログラミング言語は?(なお、ファイル数でカウントする。一番作ってるものはそろそろ90かな)\
\n1: Python\t2: Java\t3: C言語など(C++/C# etc)\t4:JavaScript\t5: Bash\t6: Scratch",#q12
    "--------------------\n＜読むと良いことがある豆知識＞\
\n開発者が一番最初に学習した言語はPythonで、一番作ってる言語はHTML/JavaScript。20個差位でScratch!\
Scratchもまあまあやってるんだ。Pythonは20個位かな。\t読みました!最高です!\tと入力してね。",#q13
    "このプログラムv1.1配布3度目は、stable(安定版)何番でしょう。",#q14
    
]

QuizAnswer=[
    #クイズの答えを入力する
    "Python",
    "1.1",
    "45",
    "4",
    "1",
    "29",
    "2",
    "4",
    "SeedofStory",
    "1",
    "1",
    "4",
    "読みました!最高です!",
    "3",
]

QuizPoint=[
    #クイズの得点を入力する
    1,
    2,
    1,
    4,
    6,
    14,
    6,
    4,
    8,
    20,
    16,
    16,
    32,
    32,
]

QuizHint=[
    "Py...?",
    "1.1....?",
    None,
    None,
    None,
    "後半です。v1.0.1以降の開発は11月からです",
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
]

QuizCheck=[
    #ゆるくチェックするか選択する(Trueだとゆるくチェック(あとア、Aとaなど),Falseだと完全一致でないと正解にしない)
    True,
    True,
    True,
    True,
    True,
    True,
    True,
    True,
    True,
    True,
    True,
    True,
    True,
    True,
    True,
    True,
    True,
    True,
    True,
    True,
    True,
    True,
    True,
    True,
    True,
    True,
    True,
    True,
    True,
    True,
    True,
    True,
    True,
    True,
    True,
    True,
    True,
    True,
    True,
    True,
    True,
    True,
    True,
]